In [2]:
# importer les librairies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
cd

C:\Users\AUDREY

In [4]:
#importerles données
dataset = pd.read_excel('child_and_demog.xlsx') 
#dataset.head()
print(dataset)

                                           Unnamed: 0  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5         8 Inequalities in maternal and child health
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                          HDI\nRank
11                             HIGH HUMAN DEVELOPMENT
12                                                 70
13                           MEDIUM HUMAN DEVELOPMENT
14                                                 73
15                                                 75
16                                                 78
17                                                 79
18                                                 83
19                                                 84
20                                                 86
21                                                 87
22                                                 90
23                                                 95
24                                                105
25                                                107
26                                                109
27                                                110
28                                                111
29                                                112
..                                                ...
59                                                157
60                                                158
61                                                159
62                                                160
63                                                161
64                                                163
65                                                164
66                                                165
67                                                166
68                                                169
69                                                170
70                                                171
71                                                172
72                                                173
73                                                174
74                                                176
75                                                177
76                                                NaN
77                                                NaN
78                                                NaN
79                                                NaN
80                                                NaN
81                                                NaN
82                                                NaN
83                                              NOTES
84  This table presents data for developing countr...
85  a. Includes tuberculosis (BCG), measles or mea...
86                                                NaN
87                                                NaN
88  SOURCES\nAll columns: Macro International 2007...

                           Unnamed: 1 Unnamed: 2   Unnamed: 3  Unnamed: 4  \
0   …to lead a long and healthy life…        NaN          NaN         NaN
1                                 NaN        NaN          NaN         NaN
2                                 NaN        NaN          NaN         NaN
3                                 NaN        NaN          NaN         NaN
4                                 NaN        NaN          NaN         NaN
5                                 NaN        NaN          NaN         NaN
6                                 NaN        NaN          NaN         NaN
7                                 NaN        NaN          NaN         NaN
8                                 NaN        NaN          NaN         NaN
9                                 NaN        NaN          NaN         NaN
10                                NaN        NaN  Survey year         NaN
11                                NaN        NaN          NaN         NaN
12                             Brazil        NaN         1996         NaN
13                                NaN        NaN          NaN         NaN
14                         Kazakhstan        NaN         1999         NaN
15                           Colombia        NaN         2005         NaN
16                           Thailand          d      2005-06         NaN
17                 Dominican Republic        NaN         1996         NaN
18                            Armenia        NaN         2005         NaN
19                             Turkey        NaN         1998         NaN
20                             Jordan        NaN         1997         NaN
21                               Peru        NaN      2004-05         NaN
22                        Philippines        NaN         2003         NaN
23                           Paraguay        NaN         1990         NaN
24                           Viet Nam        NaN         2002         NaN
25                          Indonesia        NaN         1997         NaN
26                       Turkmenistan        NaN         2000         NaN
27                          Nicaragua        NaN         2001         NaN
28                            Moldova        NaN         2005         NaN
29                              Egypt        NaN         2005         NaN
..                                ...        ...          ...         ...
59                            Eritrea        NaN         2002         NaN
60                            Nigeria        NaN         2003         NaN
61      Tanzania (United Republic of)        NaN         1999         NaN
62                             Guinea        NaN         2005         NaN
63                             Rwanda        NaN         2005         NaN
64                              Benin        NaN         2001         NaN
65                             Malawi        d,h         2000         NaN
66                             Zambia        NaN      2001-02         NaN
67                      Côte d'Ivoire        NaN         2005         NaN
68                           Ethiopia        NaN         2005         NaN
69                               Chad        NaN         2004         NaN
70           Central African Republic        NaN      1994-95         NaN
71                         Mozambique        NaN         2003         NaN
72                               Mali        NaN         2001         NaN
73                              Niger        NaN         2006         NaN
74                       Burkina Faso        NaN         2003         NaN
75                       Sierra Leone        d,h         2005         NaN
76                                NaN        NaN          NaN         NaN
77                                NaN        NaN          NaN         NaN
78                                NaN        NaN          NaN         NaN
79                                NaN        NaN          NaN         NaN
80                                NaN        NaN          NaN         NaN
81                                NaN        NaN          NaN         NaN
82                                NaN        NaN          NaN         NaN
83                                NaN        NaN          NaN         NaN
84                                NaN        NaN          NaN         NaN
85                                NaN        NaN          NaN         NaN
86                                NaN        NaN          NaN         NaN
87                                NaN        NaN          NaN         NaN
88                                NaN        NaN          NaN         NaN

                                           Unnamed: 5  Unnamed: 6  \
0                                                 NaN         NaN
1                                                 NaN         NaN
2                                                 NaN         NaN
3                                                 NaN         NaN
4                                                 NaN         NaN
5                                                 NaN         NaN
6                                                 NaN         NaN
7   Births attended by skilled health personnel \n(%)         NaN
8                                                 NaN         NaN
9                                         Poorest 20%         NaN
10                                                NaN         NaN
11                                                NaN         NaN
12                                                 72         NaN
13                                                NaN         NaN
14                                                 99         NaN
15                                                 72         NaN
16                                                 93         NaN
17                                                 89         NaN
18                                                 96         NaN
19                                                 53         NaN
20                                                 91         NaN
21                                                 34         NaN
22                                                 25         NaN
23                                                 41         NaN
24                                                 58         NaN
25                                                 21         NaN
26                                                 97         NaN
27                                                 78         NaN
28                                                 99         NaN
29                                                 51         NaN
..                                                ...         ...
59                                                  7         NaN
60                                                 12         NaN
61                                                 29         NaN
62                                                 15         NaN
63                                                 27         NaN
64                                                 50         NaN
65                                                 43         NaN
66                                                 20         NaN
67                                                 27         NaN
68                                                  1         NaN
69                                                  4         NaN
70                                                 14         NaN
71                                                 25         NaN
72                                                  8         NaN
73                                                 21         NaN
74                                                 39         NaN
75                                                 27         NaN
76                                                NaN         NaN
77                                                NaN         NaN
78                                                NaN         NaN
79                                                NaN         NaN
80                                                NaN         NaN
81                                                NaN         NaN
82                                                NaN         NaN
83                                                NaN         NaN
84                                                NaN         NaN
85                                                NaN         NaN
86                                                NaN         NaN
87                                                NaN         NaN
88                                                NaN         NaN

     Unnamed: 7  Unnamed: 8                           Unnamed: 9     ...      \
0           NaN         NaN                                  NaN     ...
1           NaN         NaN                                  NaN     ...
2           NaN         NaN                                  NaN     ...
3           NaN         NaN                                  NaN     ...
4           NaN         NaN                                  NaN     ...
5           NaN         NaN                                  NaN     ...
6           NaN         NaN                                  NaN     ...
7           NaN         NaN  One-year-olds fully immunizeda\n(%)     ...
8           NaN         NaN                                  NaN     ...
9   Richest 20%         NaN                          Poorest 20%     ...
10          NaN         NaN                                  NaN     ...
11          NaN         NaN                                  NaN     ...
12           99         NaN                                   57     ...
13          NaN         NaN                                  NaN     ...
14           99         NaN                                   69     ...
15           99         NaN                                   47     ...
16          100         NaN                                   92     ...
17           98         NaN                                   34     ...
18          100         NaN                                   59     ...
19           98         NaN                                   28     ...
20           99         NaN                                   21     ...
21          100         NaN                                   65     ...
22           92         NaN                                   56     ...
23           98         NaN                                   20     ...
24          100         NaN                                   44     ...
25           89         NaN                                   43     ...
26           98         NaN                                   85     ...
27           99         NaN                                   64     ...
28          100         NaN                                   86     ...
29           96         NaN                                   85     ...
..          ...         ...                                  ...     ...
59           81         NaN                                   74     ...
60           84         NaN                                    3     ...
61           83         NaN                                   53     ...
62           87         NaN                                   29     ...
63           66         NaN                                   74     ...
64           99         NaN                                   49     ...
65           83         NaN                                   65     ...
66           91         NaN                                   64     ...
67           88         NaN                                   ..     ...
68           27         NaN                                   14     ...
69           55         NaN                                    1     ...
70           82         NaN                                   18     ...
71           89         NaN                                   45     ...
72           82         NaN                                   20     ...
73           71         NaN                                   20     ...
74           91         NaN                                   34     ...
75           83         NaN                                   ..     ...
76          NaN         NaN                                  NaN     ...
77          NaN         NaN                                  NaN     ...
78          NaN         NaN                                  NaN     ...
79          NaN         NaN                                  NaN     ...
80          NaN         NaN                                  NaN     ...
81          NaN         NaN                                  NaN     ...
82          NaN         NaN                                  NaN     ...
83          NaN         NaN                                  NaN     ...
84          NaN         NaN                                  NaN     ...
85          NaN         NaN                                  NaN     ...
86          NaN         NaN                                  NaN     ...
87          NaN         NaN                                  NaN     ...
88          NaN         NaN                                  NaN     ...

    Unnamed: 15 Unnamed: 16                                      Unnamed: 17  \
0           NaN         NaN                                              NaN
1           NaN         NaN                                              NaN
2           NaN         NaN                                              NaN
3           NaN         NaN                                              NaN
4           NaN         NaN                                              NaN
5           NaN         NaN                                              NaN
6           NaN         NaN                                              NaN
7           NaN         NaN  Infant mortality rateb\n(per 1,000 live births)
8           NaN         NaN                                              NaN
9   Richest 20%         NaN                                      Poorest 20%
10          NaN         NaN                                              NaN
11          NaN         NaN                                              NaN
12            2         NaN                                               83
13          NaN         NaN                                              NaN
14            8         NaN                                               68
15            3         NaN                                               32
16            7         NaN                                               ..
17            2         NaN                                               67
18            8         NaN                                               41
19            4         NaN                                               68
20            5         NaN                                               35
21            4         NaN                                               46
22           ..         NaN                                               42
23            3         NaN                                               43
24           ..         NaN                                               39
25           ..         NaN                                               78
26           17         NaN                                               89
27            5         NaN                                               50
28            6         NaN                                               20
29           14         NaN                                               59
..          ...         ...                                              ...
59           18         NaN                                               48
60           18         NaN                                              133
61           23         NaN                                              115
62           22         NaN                                              127
63           30         NaN                                              114
64           18         NaN                                              112
65           23         NaN                                              132
66           32         NaN                                              115
67           ..         NaN                                               93
68           35         NaN                                               80
69           32         NaN                                              109
70           25         NaN                                              132

In [ ]:
source= "Users\AUDREY\child_and_demog"
df= pd.read_excel(source)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 25 columns):
Unnamed: 0     71 non-null object
Unnamed: 1     63 non-null object
Unnamed: 2     5 non-null object
Unnamed: 3     63 non-null object
Unnamed: 4     0 non-null float64
Unnamed: 5     64 non-null object
Unnamed: 6     0 non-null float64
Unnamed: 7     63 non-null object
Unnamed: 8     0 non-null float64
Unnamed: 9     64 non-null object
Unnamed: 10    13 non-null object
Unnamed: 11    63 non-null object
Unnamed: 12    14 non-null object
Unnamed: 13    64 non-null object
Unnamed: 14    0 non-null float64
Unnamed: 15    63 non-null object
Unnamed: 16    0 non-null float64
Unnamed: 17    64 non-null object
Unnamed: 18    1 non-null object
Unnamed: 19    63 non-null object
Unnamed: 20    1 non-null object
Unnamed: 21    64 non-null object
Unnamed: 22    1 non-null object
Unnamed: 23    63 non-null object
Unnamed: 24    2 non-null object
dtypes: float64(5), object(20)
memory usage: 10.5+ KB

In [6]:
dataset.head(13)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,…to lead a long and healthy life…,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,8 Inequalities in maternal and child health,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,Births attended by skilled health personnel \n(%),NaN,NaN,NaN,One-year-olds fully immunizeda\n(%),...,NaN,NaN,"Infant mortality rateb\n(per 1,000 live births)",NaN,NaN,NaN,"Under-five mortality rateb\n(per 1,000 live bi...",NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,Poorest 20%,NaN,Richest 20%,NaN,Poorest 20%,...,Richest 20%,NaN,Poorest 20%,NaN,Richest 20%,NaN,Poorest 20%,NaN,Richest 20%,NaN
10,HDI\nRank,NaN,NaN,Survey year,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,70,Brazil,NaN,1996,NaN,72,NaN,99,NaN,57,...,2,NaN,83,NaN,29,NaN,99,NaN,33,NaN

In [7]:
# Repositionner la ligne d'en-tête
dataset = pd.read_excel('child_and_demog.xlsx', header=7)
# https://stackoverflow.com/a/51794989
# Supprimez d'abord toutes les colonnes (axe=1) sans valeurs
dataset = dataset.dropna(how="all", axis=1)
# Supprimer toutes les lignes (axe=0) sans valeurs
dataset = dataset.dropna(how="all", axis=0).reset_index(drop=True)
#df.head(6)

In [8]:
dataset

,8 Inequalities in maternal and child health,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 5,Unnamed: 7,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 15,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,NaN,NaN,NaN,Births attended by skilled health personnel \n(%),NaN,One-year-olds fully immunizeda\n(%),NaN,NaN,NaN,Children under height for age \n(% under age 5),NaN,"Infant mortality rateb\n(per 1,000 live births)",NaN,NaN,NaN,"Under-five mortality rateb\n(per 1,000 live bi...",NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Poorest 20%,Richest 20%,Poorest 20%,NaN,Richest 20%,NaN,Poorest 20%,Richest 20%,Poorest 20%,NaN,Richest 20%,NaN,Poorest 20%,NaN,Richest 20%,NaN
2,HDI\nRank,NaN,NaN,Survey year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,70,Brazil,NaN,1996,72,99,57,NaN,74,NaN,23,2,83,NaN,29,NaN,99,NaN,33,NaN
5,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,73,Kazakhstan,NaN,1999,99,99,69,NaN,62,c,15,8,68,NaN,42,NaN,82,NaN,45,NaN
7,75,Colombia,NaN,2005,72,99,47,NaN,72,NaN,20,3,32,NaN,14,NaN,39,NaN,16,NaN
8,78,Thailand,d,2005-06,93,100,92,e,86,e,16,7,..,NaN,..,NaN,..,NaN,..,NaN
9,79,Dominican Republic,NaN,1996,89,98,34,NaN,47,NaN,14,2,67,NaN,23,NaN,90,NaN,27,NaN
10,83,Armenia,NaN,2005,96,100,59,e,51,"c,e",15,8,41,NaN,14,NaN,52,NaN,23,NaN
11,84,Turkey,NaN,1998,53,98,28,NaN,70,NaN,29,4,68,NaN,30,NaN,85,NaN,33,NaN
12,86,Jordan,NaN,1997,91,99,21,NaN,17,NaN,14,5,35,NaN,23,NaN,42,NaN,25,NaN
13,87,Peru,NaN,2004-05,34,100,65,e,73,e,46,4,46,NaN,6,NaN,63,NaN,11,NaN
14,90,Philippines,NaN,2003,25,92,56,NaN,83,NaN,..,..,42,NaN,19,NaN,66,NaN,21,NaN
15,95,Paraguay,NaN,1990,41,98,20,NaN,53,NaN,23,3,43,NaN,16,NaN,57,NaN,20,NaN
16,105,Viet Nam,NaN,2002,58,100,44,NaN,92,NaN,..,..,39,NaN,14,NaN,53,NaN,16,NaN
17,107,Indonesia,NaN,1997,21,89,43,NaN,72,NaN,..,..,78,NaN,23,NaN,109,NaN,29,NaN
18,109,Turkmenistan,NaN,2000,97,98,85,NaN,78,NaN,25,17,89,NaN,58,NaN,106,NaN,70,NaN
19,110,Nicaragua,NaN,2001,78,99,64,NaN,71,NaN,35,5,50,NaN,16,NaN,64,NaN,19,NaN
20,111,Moldova,NaN,2005,99,100,86,"c,f",86,f,14,6,20,NaN,16,NaN,29,NaN,17,NaN
21,112,Egypt,NaN,2005,51,96,85,e,91,e,24,14,59,NaN,23,NaN,75,NaN,25,NaN
22,113,Uzbekistan,NaN,1996,92,100,81,NaN,78,NaN,40,31,54,NaN,46,NaN,70,NaN,50,NaN
23,116,Kyrgyzstan,NaN,1997,96,100,69,NaN,73,NaN,34,14,83,NaN,46,NaN,96,NaN,49,NaN
24,117,Bolivia,NaN,2003,27,98,48,e,57,e,42,5,72,g,27,g,105,g,32,g
25,118,Guatemala,NaN,1998-99,9,92,66,NaN,56,NaN,65,8,58,NaN,39,NaN,78,NaN,39,NaN
26,119,Gabon,NaN,2000,67,97,6,NaN,24,NaN,33,12,57,NaN,36,NaN,93,NaN,55,NaN
27,121,South Africa,NaN,1998,68,98,51,NaN,70,NaN,..,..,62,NaN,17,NaN,87,NaN,22,NaN
28,122,Tajikistan,"d,h",2006,69,91,..,NaN,..,NaN,32,21,..,NaN,..,NaN,..,NaN,..,NaN
29,125,Namibia,NaN,2000,55,97,60,NaN,68,NaN,27,15,36,NaN,23,NaN,55,NaN,31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,144,Cameroon,NaN,2004,29,94,36,NaN,60,NaN,41,12,101,NaN,51,NaN,189,NaN,88,NaN
43,146,Haiti,NaN,2005-06,6,68,34,NaN,56,NaN,34,5,78,NaN,45,NaN,125,NaN,55,NaN
44,148,Kenya,NaN,2003,17,75,40,f,65,f,38,19,96,NaN,62,NaN,149,NaN,91,NaN
45,151,Zimbabwe,NaN,1999,57,94,64,NaN,64,NaN,33,19,59,NaN,44,NaN,100,NaN,62,NaN
46,152,Togo,NaN,1998,25,91,22,NaN,52,NaN,29,11,84,NaN,66,NaN,168,NaN,97,NaN
47,153,Yemen,NaN,1997,7,50,8,NaN,56,NaN,58,35,109,NaN,60,NaN,163,NaN,73,NaN
48,154,Uganda,NaN,2000-01,20,77,27,NaN,43,NaN,43,25,106,NaN,60,NaN,192,NaN,106,NaN
49,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,156,Senegal,NaN,2005,20,89,59,NaN,65,NaN,26,6,89,NaN,41,NaN,183,NaN,64,NaN
51,157,Eritrea,NaN,2002,7,81,74,NaN,91,NaN,45,18,48,NaN,38,NaN,100,NaN,65,NaN
52,158,Nigeria,NaN,2003,12,84,3,NaN,40,NaN,49,18,133,NaN,52,NaN,257,NaN,79,NaN
53,159,Tanzania (United Republic of),NaN,1999,29,83,53,NaN,78,NaN,50,23,115,NaN,92,NaN,160,NaN,135,NaN
54,160,Guinea,NaN,2005,15,87,29,NaN,45,NaN,41,22,127,NaN,68,NaN,217,NaN,113,NaN
55,161,Rwanda,NaN,2005,27,66,74,NaN,74,NaN,55,30,114,NaN,73,NaN,211,NaN,122,NaN
56,163,Benin,NaN,2001,50,99,49,NaN,73,NaN,35,18,112,NaN,50,NaN,198,NaN,93,NaN
57,164,Malawi,"d,h",2000,43,83,65,NaN,81,NaN,26,23,132,NaN,86,NaN,231,NaN,149,NaN
58,165,Zambia,NaN,2001-02,20,91,64,NaN,80,NaN,54,32,115,NaN,57,NaN,192,NaN,92,NaN
59,166,Côte d'Ivoire,NaN,2005,27,88,..,NaN,..,NaN,..,..,93,NaN,79,NaN,150,NaN,100,NaN
60,169,Ethiopia,NaN,2005,1,27,14,NaN,36,NaN,48,35,80,NaN,60,NaN,130,NaN,92,NaN
61,170,Chad,NaN,2004,4,55,1,NaN,24,NaN,51,32,109,NaN,101,NaN,176,NaN,187,NaN
62,171,Central African Republic,NaN,1994-95,14,82,18,NaN,64,NaN,42,25,132,NaN,54,NaN,193,NaN,98,NaN
63,172,Mozambique,NaN,2003,25,89,45,NaN,90,NaN,49,20,143,NaN,71,NaN,196,NaN,108,NaN
64,173,Mali,NaN,2001,8,82,20,NaN,56,NaN,45,20,137,NaN,90,NaN,248,NaN,148,NaN
65,174,Niger,NaN,2006,21,71,20,NaN,48,NaN,54,37,91,NaN,67,NaN,206,NaN,157,NaN
66,176,Burkina Faso,NaN,2003,39,91,34,NaN,61,NaN,46,21,97,NaN,78,NaN,206,NaN,144,NaN
67,177,Sierra Leone,"d,h",2005,27,83,..,NaN,..,NaN,44,26,159,NaN,108,NaN,268,NaN,179,NaN
68,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,This table presents data for developing countr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,"a. Includes tuberculosis (BCG), measles or mea...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,SOURCES\nAll columns: Macro International 2007...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
columns = []
for i in dataset.columns:
    # Pour chaque colonne, obtenir les valeurs des 5 premières lignes
    # puis conservez toutes les chaînes (c'est-à-dire excluez-les si elles sont nulles) et ajoutez-les en colonne
    columns.append([str(v) for v in dataset[i][:4] if pd.notnull(v)])
columns

[['HDI\nRank', 'HIGH HUMAN DEVELOPMENT'],
 [],
 [],
 ['Survey year'],
 ['Births attended by skilled health personnel \n(%)', 'Poorest 20%'],
 ['Richest 20%'],
 ['One-year-olds fully immunizeda\n(%)', 'Poorest 20%'],
 [],
 ['Richest 20%'],
 [],
 ['Children under height for age \n(% under age 5)  ', 'Poorest 20%'],
 ['Richest 20%'],
 ['Infant mortality rateb\n(per 1,000 live births)', 'Poorest 20%'],
 [],
 ['Richest 20%'],
 [],
 ['Under-five mortality rateb\n(per 1,000 live births)', 'Poorest 20%'],
 [],
 ['Richest 20%'],
 []]

In [10]:
columns = [
    "HDI_rank",
    "Country",
    "Reference 1",
    "Survey_year",
    "Birth_attended_Poor",
    "Birth_attended_Rich",
    "One-year-olds  immunized_Poor",
    "Reference 2",
    "One-year-olds  immunized_Rich",
    "Reference 3",
    "Child_underheight_ Poor",
    "Child_underheight_ Rich",
    "IMR_Poor",
    "Reference 4",
    "IMR_Rich",
    "Reference 5",
    "Under5_MR_Poor",
    "Reference 6",
    "Under5_MR_Rich",
    "Reference 7"
]

In [11]:
columns

['HDI_rank',
 'Country',
 'Reference 1',
 'Survey_year',
 'Birth_attended_Poor',
 'Birth_attended_Rich',
 'One-year-olds  immunized_Poor',
 'Reference 2',
 'One-year-olds  immunized_Rich',
 'Reference 3',
 'Child_underheight_ Poor',
 'Child_underheight_ Rich',
 'IMR_Poor',
 'Reference 4',
 'IMR_Rich',
 'Reference 5',
 'Under5_MR_Poor',
 'Reference 6',
 'Under5_MR_Rich',
 'Reference 7']

In [12]:
# Réinitialiser les colonnes des cadres de données
dataset.columns=columns

In [13]:
dataset

,HDI_rank,Country,Reference 1,Survey_year,Birth_attended_Poor,Birth_attended_Rich,One-year-olds immunized_Poor,Reference 2,One-year-olds immunized_Rich,Reference 3,Child_underheight_ Poor,Child_underheight_ Rich,IMR_Poor,Reference 4,IMR_Rich,Reference 5,Under5_MR_Poor,Reference 6,Under5_MR_Rich,Reference 7
0,NaN,NaN,NaN,NaN,Births attended by skilled health personnel \n(%),NaN,One-year-olds fully immunizeda\n(%),NaN,NaN,NaN,Children under height for age \n(% under age 5),NaN,"Infant mortality rateb\n(per 1,000 live births)",NaN,NaN,NaN,"Under-five mortality rateb\n(per 1,000 live bi...",NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Poorest 20%,Richest 20%,Poorest 20%,NaN,Richest 20%,NaN,Poorest 20%,Richest 20%,Poorest 20%,NaN,Richest 20%,NaN,Poorest 20%,NaN,Richest 20%,NaN
2,HDI\nRank,NaN,NaN,Survey year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,70,Brazil,NaN,1996,72,99,57,NaN,74,NaN,23,2,83,NaN,29,NaN,99,NaN,33,NaN
5,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,73,Kazakhstan,NaN,1999,99,99,69,NaN,62,c,15,8,68,NaN,42,NaN,82,NaN,45,NaN
7,75,Colombia,NaN,2005,72,99,47,NaN,72,NaN,20,3,32,NaN,14,NaN,39,NaN,16,NaN
8,78,Thailand,d,2005-06,93,100,92,e,86,e,16,7,..,NaN,..,NaN,..,NaN,..,NaN
9,79,Dominican Republic,NaN,1996,89,98,34,NaN,47,NaN,14,2,67,NaN,23,NaN,90,NaN,27,NaN
10,83,Armenia,NaN,2005,96,100,59,e,51,"c,e",15,8,41,NaN,14,NaN,52,NaN,23,NaN
11,84,Turkey,NaN,1998,53,98,28,NaN,70,NaN,29,4,68,NaN,30,NaN,85,NaN,33,NaN
12,86,Jordan,NaN,1997,91,99,21,NaN,17,NaN,14,5,35,NaN,23,NaN,42,NaN,25,NaN
13,87,Peru,NaN,2004-05,34,100,65,e,73,e,46,4,46,NaN,6,NaN,63,NaN,11,NaN
14,90,Philippines,NaN,2003,25,92,56,NaN,83,NaN,..,..,42,NaN,19,NaN,66,NaN,21,NaN
15,95,Paraguay,NaN,1990,41,98,20,NaN,53,NaN,23,3,43,NaN,16,NaN,57,NaN,20,NaN
16,105,Viet Nam,NaN,2002,58,100,44,NaN,92,NaN,..,..,39,NaN,14,NaN,53,NaN,16,NaN
17,107,Indonesia,NaN,1997,21,89,43,NaN,72,NaN,..,..,78,NaN,23,NaN,109,NaN,29,NaN
18,109,Turkmenistan,NaN,2000,97,98,85,NaN,78,NaN,25,17,89,NaN,58,NaN,106,NaN,70,NaN
19,110,Nicaragua,NaN,2001,78,99,64,NaN,71,NaN,35,5,50,NaN,16,NaN,64,NaN,19,NaN
20,111,Moldova,NaN,2005,99,100,86,"c,f",86,f,14,6,20,NaN,16,NaN,29,NaN,17,NaN
21,112,Egypt,NaN,2005,51,96,85,e,91,e,24,14,59,NaN,23,NaN,75,NaN,25,NaN
22,113,Uzbekistan,NaN,1996,92,100,81,NaN,78,NaN,40,31,54,NaN,46,NaN,70,NaN,50,NaN
23,116,Kyrgyzstan,NaN,1997,96,100,69,NaN,73,NaN,34,14,83,NaN,46,NaN,96,NaN,49,NaN
24,117,Bolivia,NaN,2003,27,98,48,e,57,e,42,5,72,g,27,g,105,g,32,g
25,118,Guatemala,NaN,1998-99,9,92,66,NaN,56,NaN,65,8,58,NaN,39,NaN,78,NaN,39,NaN
26,119,Gabon,NaN,2000,67,97,6,NaN,24,NaN,33,12,57,NaN,36,NaN,93,NaN,55,NaN
27,121,South Africa,NaN,1998,68,98,51,NaN,70,NaN,..,..,62,NaN,17,NaN,87,NaN,22,NaN
28,122,Tajikistan,"d,h",2006,69,91,..,NaN,..,NaN,32,21,..,NaN,..,NaN,..,NaN,..,NaN
29,125,Namibia,NaN,2000,55,97,60,NaN,68,NaN,27,15,36,NaN,23,NaN,55,NaN,31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,144,Cameroon,NaN,2004,29,94,36,NaN,60,NaN,41,12,101,NaN,51,NaN,189,NaN,88,NaN
43,146,Haiti,NaN,2005-06,6,68,34,NaN,56,NaN,34,5,78,NaN,45,NaN,125,NaN,55,NaN
44,148,Kenya,NaN,2003,17,75,40,f,65,f,38,19,96,NaN,62,NaN,149,NaN,91,NaN
45,151,Zimbabwe,NaN,1999,57,94,64,NaN,64,NaN,33,19,59,NaN,44,NaN,100,NaN,62,NaN
46,152,Togo,NaN,1998,25,91,22,NaN,52,NaN,29,11,84,NaN,66,NaN,168,NaN,97,NaN
47,153,Yemen,NaN,1997,7,50,8,NaN,56,NaN,58,35,109,NaN,60,NaN,163,NaN,73,NaN
48,154,Uganda,NaN,2000-01,20,77,27,NaN,43,NaN,43,25,106,NaN,60,NaN,192,NaN,106,NaN
49,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,156,Senegal,NaN,2005,20,89,59,NaN,65,NaN,26,6,89,NaN,41,NaN,183,NaN,64,NaN
51,157,Eritrea,NaN,2002,7,81,74,NaN,91,NaN,45,18,48,NaN,38,NaN,100,NaN,65,NaN
52,158,Nigeria,NaN,2003,12,84,3,NaN,40,NaN,49,18,133,NaN,52,NaN,257,NaN,79,NaN
53,159,Tanzania (United Republic of),NaN,1999,29,83,53,NaN,78,NaN,50,23,115,NaN,92,NaN,160,NaN,135,NaN
54,160,Guinea,NaN,2005,15,87,29,NaN,45,NaN,41,22,127,NaN,68,NaN,217,NaN,113,NaN
55,161,Rwanda,NaN,2005,27,66,74,NaN,74,NaN,55,30,114,NaN,73,NaN,211,NaN,122,NaN
56,163,Benin,NaN,2001,50,99,49,NaN,73,NaN,35,18,112,NaN,50,NaN,198,NaN,93,NaN
57,164,Malawi,"d,h",2000,43,83,65,NaN,81,NaN,26,23,132,NaN,86,NaN,231,NaN,149,NaN
58,165,Zambia,NaN,2001-02,20,91,64,NaN,80,NaN,54,32,115,NaN,57,NaN,192,NaN,92,NaN
59,166,Côte d'Ivoire,NaN,2005,27,88,..,NaN,..,NaN,..,..,93,NaN,79,NaN,150,NaN,100,NaN
60,169,Ethiopia,NaN,2005,1,27,14,NaN,36,NaN,48,35,80,NaN,60,NaN,130,NaN,92,NaN
61,170,Chad,NaN,2004,4,55,1,NaN,24,NaN,51,32,109,NaN,101,NaN,176,NaN,187,NaN
62,171,Central African Republic,NaN,1994-95,14,82,18,NaN,64,NaN,42,25,132,NaN,54,NaN,193,NaN,98,NaN
63,172,Mozambique,NaN,2003,25,89,45,NaN,90,NaN,49,20,143,NaN,71,NaN,196,NaN,108,NaN
64,173,Mali,NaN,2001,8,82,20,NaN,56,NaN,45,20,137,NaN,90,NaN,248,NaN,148,NaN
65,174,Niger,NaN,2006,21,71,20,NaN,48,NaN,54,37,91,NaN,67,NaN,206,NaN,157,NaN
66,176,Burkina Faso,NaN,2003,39,91,34,NaN,61,NaN,46,21,97,NaN,78,NaN,206,NaN,144,NaN
67,177,Sierra Leone,"d,h",2005,27,83,..,NaN,..,NaN,44,26,159,NaN,108,NaN,268,NaN,179,NaN
68,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,This table presents data for developing countr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,"a. Includes tuberculosis (BCG), measles or mea...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,SOURCES\nAll columns: Macro International 2007...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
dataset = dataset.drop(np.arange(3), axis=0).reset_index(drop=True)
dataset.head()

,HDI_rank,Country,Reference 1,Survey_year,Birth_attended_Poor,Birth_attended_Rich,One-year-olds immunized_Poor,Reference 2,One-year-olds immunized_Rich,Reference 3,Child_underheight_ Poor,Child_underheight_ Rich,IMR_Poor,Reference 4,IMR_Rich,Reference 5,Under5_MR_Poor,Reference 6,Under5_MR_Rich,Reference 7
0,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,70,Brazil,NaN,1996,72,99,57,NaN,74,NaN,23,2,83,NaN,29,NaN,99,NaN,33,NaN
2,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,73,Kazakhstan,NaN,1999,99,99,69,NaN,62,c,15,8,68,NaN,42,NaN,82,NaN,45,NaN
4,75,Colombia,NaN,2005,72,99,47,NaN,72,NaN,20,3,32,NaN,14,NaN,39,NaN,16,NaN

In [15]:
dataset.tail(30)

,HDI_rank,Country,Reference 1,Survey_year,Birth_attended_Poor,Birth_attended_Rich,One-year-olds immunized_Poor,Reference 2,One-year-olds immunized_Rich,Reference 3,Child_underheight_ Poor,Child_underheight_ Rich,IMR_Poor,Reference 4,IMR_Rich,Reference 5,Under5_MR_Poor,Reference 6,Under5_MR_Rich,Reference 7
39,144,Cameroon,NaN,2004,29,94,36,NaN,60,NaN,41,12,101,NaN,51,NaN,189,NaN,88,NaN
40,146,Haiti,NaN,2005-06,6,68,34,NaN,56,NaN,34,5,78,NaN,45,NaN,125,NaN,55,NaN
41,148,Kenya,NaN,2003,17,75,40,f,65,f,38,19,96,NaN,62,NaN,149,NaN,91,NaN
42,151,Zimbabwe,NaN,1999,57,94,64,NaN,64,NaN,33,19,59,NaN,44,NaN,100,NaN,62,NaN
43,152,Togo,NaN,1998,25,91,22,NaN,52,NaN,29,11,84,NaN,66,NaN,168,NaN,97,NaN
44,153,Yemen,NaN,1997,7,50,8,NaN,56,NaN,58,35,109,NaN,60,NaN,163,NaN,73,NaN
45,154,Uganda,NaN,2000-01,20,77,27,NaN,43,NaN,43,25,106,NaN,60,NaN,192,NaN,106,NaN
46,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,156,Senegal,NaN,2005,20,89,59,NaN,65,NaN,26,6,89,NaN,41,NaN,183,NaN,64,NaN
48,157,Eritrea,NaN,2002,7,81,74,NaN,91,NaN,45,18,48,NaN,38,NaN,100,NaN,65,NaN
49,158,Nigeria,NaN,2003,12,84,3,NaN,40,NaN,49,18,133,NaN,52,NaN,257,NaN,79,NaN
50,159,Tanzania (United Republic of),NaN,1999,29,83,53,NaN,78,NaN,50,23,115,NaN,92,NaN,160,NaN,135,NaN
51,160,Guinea,NaN,2005,15,87,29,NaN,45,NaN,41,22,127,NaN,68,NaN,217,NaN,113,NaN
52,161,Rwanda,NaN,2005,27,66,74,NaN,74,NaN,55,30,114,NaN,73,NaN,211,NaN,122,NaN
53,163,Benin,NaN,2001,50,99,49,NaN,73,NaN,35,18,112,NaN,50,NaN,198,NaN,93,NaN
54,164,Malawi,"d,h",2000,43,83,65,NaN,81,NaN,26,23,132,NaN,86,NaN,231,NaN,149,NaN
55,165,Zambia,NaN,2001-02,20,91,64,NaN,80,NaN,54,32,115,NaN,57,NaN,192,NaN,92,NaN
56,166,Côte d'Ivoire,NaN,2005,27,88,..,NaN,..,NaN,..,..,93,NaN,79,NaN,150,NaN,100,NaN
57,169,Ethiopia,NaN,2005,1,27,14,NaN,36,NaN,48,35,80,NaN,60,NaN,130,NaN,92,NaN
58,170,Chad,NaN,2004,4,55,1,NaN,24,NaN,51,32,109,NaN,101,NaN,176,NaN,187,NaN
59,171,Central African Republic,NaN,1994-95,14,82,18,NaN,64,NaN,42,25,132,NaN,54,NaN,193,NaN,98,NaN
60,172,Mozambique,NaN,2003,25,89,45,NaN,90,NaN,49,20,143,NaN,71,NaN,196,NaN,108,NaN
61,173,Mali,NaN,2001,8,82,20,NaN,56,NaN,45,20,137,NaN,90,NaN,248,NaN,148,NaN
62,174,Niger,NaN,2006,21,71,20,NaN,48,NaN,54,37,91,NaN,67,NaN,206,NaN,157,NaN
63,176,Burkina Faso,NaN,2003,39,91,34,NaN,61,NaN,46,21,97,NaN,78,NaN,206,NaN,144,NaN
64,177,Sierra Leone,"d,h",2005,27,83,..,NaN,..,NaN,44,26,159,NaN,108,NaN,268,NaN,179,NaN
65,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,This table presents data for developing countr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,"a. Includes tuberculosis (BCG), measles or mea...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,SOURCES\nAll columns: Macro International 2007...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Déposer les lignes du bas des données que nous voulons conserver, jusqu'à la fin (défini comme len(df))
dataset = dataset.drop(np.arange(65,len(dataset)), axis=0).reset_index(drop=True)

In [19]:
dataset

,HDI_rank,Country,Reference 1,Survey_year,Birth_attended_Poor,Birth_attended_Rich,One-year-olds immunized_Poor,Reference 2,One-year-olds immunized_Rich,Reference 3,Child_underheight_ Poor,Child_underheight_ Rich,IMR_Poor,Reference 4,IMR_Rich,Reference 5,Under5_MR_Poor,Reference 6,Under5_MR_Rich,Reference 7
0,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,70,Brazil,NaN,1996,72,99,57,NaN,74,NaN,23,2,83,NaN,29,NaN,99,NaN,33,NaN
2,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,73,Kazakhstan,NaN,1999,99,99,69,NaN,62,c,15,8,68,NaN,42,NaN,82,NaN,45,NaN
4,75,Colombia,NaN,2005,72,99,47,NaN,72,NaN,20,3,32,NaN,14,NaN,39,NaN,16,NaN
5,78,Thailand,d,2005-06,93,100,92,e,86,e,16,7,..,NaN,..,NaN,..,NaN,..,NaN
6,79,Dominican Republic,NaN,1996,89,98,34,NaN,47,NaN,14,2,67,NaN,23,NaN,90,NaN,27,NaN
7,83,Armenia,NaN,2005,96,100,59,e,51,"c,e",15,8,41,NaN,14,NaN,52,NaN,23,NaN
8,84,Turkey,NaN,1998,53,98,28,NaN,70,NaN,29,4,68,NaN,30,NaN,85,NaN,33,NaN
9,86,Jordan,NaN,1997,91,99,21,NaN,17,NaN,14,5,35,NaN,23,NaN,42,NaN,25,NaN
10,87,Peru,NaN,2004-05,34,100,65,e,73,e,46,4,46,NaN,6,NaN,63,NaN,11,NaN
11,90,Philippines,NaN,2003,25,92,56,NaN,83,NaN,..,..,42,NaN,19,NaN,66,NaN,21,NaN
12,95,Paraguay,NaN,1990,41,98,20,NaN,53,NaN,23,3,43,NaN,16,NaN,57,NaN,20,NaN
13,105,Viet Nam,NaN,2002,58,100,44,NaN,92,NaN,..,..,39,NaN,14,NaN,53,NaN,16,NaN
14,107,Indonesia,NaN,1997,21,89,43,NaN,72,NaN,..,..,78,NaN,23,NaN,109,NaN,29,NaN
15,109,Turkmenistan,NaN,2000,97,98,85,NaN,78,NaN,25,17,89,NaN,58,NaN,106,NaN,70,NaN
16,110,Nicaragua,NaN,2001,78,99,64,NaN,71,NaN,35,5,50,NaN,16,NaN,64,NaN,19,NaN
17,111,Moldova,NaN,2005,99,100,86,"c,f",86,f,14,6,20,NaN,16,NaN,29,NaN,17,NaN
18,112,Egypt,NaN,2005,51,96,85,e,91,e,24,14,59,NaN,23,NaN,75,NaN,25,NaN
19,113,Uzbekistan,NaN,1996,92,100,81,NaN,78,NaN,40,31,54,NaN,46,NaN,70,NaN,50,NaN
20,116,Kyrgyzstan,NaN,1997,96,100,69,NaN,73,NaN,34,14,83,NaN,46,NaN,96,NaN,49,NaN
21,117,Bolivia,NaN,2003,27,98,48,e,57,e,42,5,72,g,27,g,105,g,32,g
22,118,Guatemala,NaN,1998-99,9,92,66,NaN,56,NaN,65,8,58,NaN,39,NaN,78,NaN,39,NaN
23,119,Gabon,NaN,2000,67,97,6,NaN,24,NaN,33,12,57,NaN,36,NaN,93,NaN,55,NaN
24,121,South Africa,NaN,1998,68,98,51,NaN,70,NaN,..,..,62,NaN,17,NaN,87,NaN,22,NaN
25,122,Tajikistan,"d,h",2006,69,91,..,NaN,..,NaN,32,21,..,NaN,..,NaN,..,NaN,..,NaN
26,125,Namibia,NaN,2000,55,97,60,NaN,68,NaN,27,15,36,NaN,23,NaN,55,NaN,31,NaN
27,126,Morocco,NaN,2003-04,30,95,81,e,97,e,29,10,62,NaN,24,NaN,78,NaN,26,NaN
28,128,India,NaN,1998-99,16,84,21,NaN,64,NaN,58,27,97,NaN,38,NaN,141,NaN,46,NaN
29,131,Cambodia,NaN,2005,21,90,56,e,76,e,47,19,101,NaN,34,NaN,127,NaN,43,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,139,Congo,NaN,2005,70,98,29,e,73,e,32,20,91,NaN,56,NaN,135,NaN,85,NaN
36,140,Bangladesh,NaN,2004,3,40,57,e,87,e,54,25,90,NaN,65,NaN,121,NaN,72,NaN
37,142,Nepal,NaN,2001,4,45,54,NaN,82,NaN,62,36,86,NaN,53,NaN,130,NaN,68,NaN
38,143,Madagascar,NaN,2003-04,30,94,32,NaN,80,NaN,51,38,87,NaN,33,NaN,142,NaN,49,NaN
39,144,Cameroon,NaN,2004,29,94,36,NaN,60,NaN,41,12,101,NaN,51,NaN,189,NaN,88,NaN
40,146,Haiti,NaN,2005-06,6,68,34,NaN,56,NaN,34,5,78,NaN,45,NaN,125,NaN,55,NaN
41,148,Kenya,NaN,2003,17,75,40,f,65,f,38,19,96,NaN,62,NaN,149,NaN,91,NaN
42,151,Zimbabwe,NaN,1999,57,94,64,NaN,64,NaN,33,19,59,NaN,44,NaN,100,NaN,62,NaN
43,152,Togo,NaN,1998,25,91,22,NaN,52,NaN,29,11,84,NaN,66,NaN,168,NaN,97,NaN
44,153,Yemen,NaN,1997,7,50,8,NaN,56,NaN,58,35,109,NaN,60,NaN,163,NaN,73,NaN
45,154,Uganda,NaN,2000-01,20,77,27,NaN,43,NaN,43,25,106,NaN,60,NaN,192,NaN,106,NaN
46,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,156,Senegal,NaN,2005,20,89,59,NaN,65,NaN,26,6,89,NaN,41,NaN,183,NaN,64,NaN
48,157,Eritrea,NaN,2002,7,81,74,NaN,91,NaN,45,18,48,NaN,38,NaN,100,NaN,65,NaN
49,158,Nigeria,NaN,2003,12,84,3,NaN,40,NaN,49,18,133,NaN,52,NaN,257,NaN,79,NaN
50,159,Tanzania (United Republic of),NaN,1999,29,83,53,NaN,78,NaN,50,23,115,NaN,92,NaN,160,NaN,135,NaN
51,160,Guinea,NaN,2005,15,87,29,NaN,45,NaN,41,22,127,NaN,68,NaN,217,NaN,113,NaN
52,161,Rwanda,NaN,2005,27,66,74,NaN,74,NaN,55,30,114,NaN,73,NaN,211,NaN,122,NaN
53,163,Benin,NaN,2001,50,99,49,NaN,73,NaN,35,18,112,NaN,50,NaN,198,NaN,93,NaN
54,164,Malawi,"d,h",2000,43,83,65,NaN,81,NaN,26,23,132,NaN,86,NaN,231,NaN,149,NaN
55,165,Zambia,NaN,2001-02,20,91,64,NaN,80,NaN,54,32,115,NaN,57,NaN,192,NaN,92,NaN
56,166,Côte d'Ivoire,NaN,2005,27,88,..,NaN,..,NaN,..,..,93,NaN,79,NaN,150,NaN,100,NaN
57,169,Ethiopia,NaN,2005,1,27,14,NaN,36,NaN,48,35,80,NaN,60,NaN,130,NaN,92,NaN
58,170,Chad,NaN,2004,4,55,1,NaN,24,NaN,51,32,109,NaN,101,NaN,176,NaN,187,NaN
59,171,Central African Republic,NaN,1994-95,14,82,18,NaN,64,NaN,42,25,132,NaN,54,NaN,193,NaN,98,NaN
60,172,Mozambique,NaN,2003,25,89,45,NaN,90,NaN,49,20,143,NaN,71,NaN,196,NaN,108,NaN
61,173,Mali,NaN,2001,8,82,20,NaN,56,NaN,45,20,137,NaN,90,NaN,248,NaN,148,NaN
62,174,Niger,NaN,2006,21,71,20,NaN,48,NaN,54,37,91,NaN,67,NaN,206,NaN,157,NaN
63,176,Burkina Faso,NaN,2003,39,91,34,NaN,61,NaN,46,21,97,NaN,78,NaN,206,NaN,144,NaN
64,177,Sierra Leone,"d,h",2005,27,83,..,NaN,..,NaN,44,26,159,NaN,108,NaN,268,NaN,179,NaN

In [20]:
dataset.tail(30)

,HDI_rank,Country,Reference 1,Survey_year,Birth_attended_Poor,Birth_attended_Rich,One-year-olds immunized_Poor,Reference 2,One-year-olds immunized_Rich,Reference 3,Child_underheight_ Poor,Child_underheight_ Rich,IMR_Poor,Reference 4,IMR_Rich,Reference 5,Under5_MR_Poor,Reference 6,Under5_MR_Rich,Reference 7
35,139,Congo,NaN,2005,70,98,29,e,73,e,32,20,91,NaN,56,NaN,135,NaN,85,NaN
36,140,Bangladesh,NaN,2004,3,40,57,e,87,e,54,25,90,NaN,65,NaN,121,NaN,72,NaN
37,142,Nepal,NaN,2001,4,45,54,NaN,82,NaN,62,36,86,NaN,53,NaN,130,NaN,68,NaN
38,143,Madagascar,NaN,2003-04,30,94,32,NaN,80,NaN,51,38,87,NaN,33,NaN,142,NaN,49,NaN
39,144,Cameroon,NaN,2004,29,94,36,NaN,60,NaN,41,12,101,NaN,51,NaN,189,NaN,88,NaN
40,146,Haiti,NaN,2005-06,6,68,34,NaN,56,NaN,34,5,78,NaN,45,NaN,125,NaN,55,NaN
41,148,Kenya,NaN,2003,17,75,40,f,65,f,38,19,96,NaN,62,NaN,149,NaN,91,NaN
42,151,Zimbabwe,NaN,1999,57,94,64,NaN,64,NaN,33,19,59,NaN,44,NaN,100,NaN,62,NaN
43,152,Togo,NaN,1998,25,91,22,NaN,52,NaN,29,11,84,NaN,66,NaN,168,NaN,97,NaN
44,153,Yemen,NaN,1997,7,50,8,NaN,56,NaN,58,35,109,NaN,60,NaN,163,NaN,73,NaN
45,154,Uganda,NaN,2000-01,20,77,27,NaN,43,NaN,43,25,106,NaN,60,NaN,192,NaN,106,NaN
46,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,156,Senegal,NaN,2005,20,89,59,NaN,65,NaN,26,6,89,NaN,41,NaN,183,NaN,64,NaN
48,157,Eritrea,NaN,2002,7,81,74,NaN,91,NaN,45,18,48,NaN,38,NaN,100,NaN,65,NaN
49,158,Nigeria,NaN,2003,12,84,3,NaN,40,NaN,49,18,133,NaN,52,NaN,257,NaN,79,NaN
50,159,Tanzania (United Republic of),NaN,1999,29,83,53,NaN,78,NaN,50,23,115,NaN,92,NaN,160,NaN,135,NaN
51,160,Guinea,NaN,2005,15,87,29,NaN,45,NaN,41,22,127,NaN,68,NaN,217,NaN,113,NaN
52,161,Rwanda,NaN,2005,27,66,74,NaN,74,NaN,55,30,114,NaN,73,NaN,211,NaN,122,NaN
53,163,Benin,NaN,2001,50,99,49,NaN,73,NaN,35,18,112,NaN,50,NaN,198,NaN,93,NaN
54,164,Malawi,"d,h",2000,43,83,65,NaN,81,NaN,26,23,132,NaN,86,NaN,231,NaN,149,NaN
55,165,Zambia,NaN,2001-02,20,91,64,NaN,80,NaN,54,32,115,NaN,57,NaN,192,NaN,92,NaN
56,166,Côte d'Ivoire,NaN,2005,27,88,..,NaN,..,NaN,..,..,93,NaN,79,NaN,150,NaN,100,NaN
57,169,Ethiopia,NaN,2005,1,27,14,NaN,36,NaN,48,35,80,NaN,60,NaN,130,NaN,92,NaN
58,170,Chad,NaN,2004,4,55,1,NaN,24,NaN,51,32,109,NaN,101,NaN,176,NaN,187,NaN
59,171,Central African Republic,NaN,1994-95,14,82,18,NaN,64,NaN,42,25,132,NaN,54,NaN,193,NaN,98,NaN
60,172,Mozambique,NaN,2003,25,89,45,NaN,90,NaN,49,20,143,NaN,71,NaN,196,NaN,108,NaN
61,173,Mali,NaN,2001,8,82,20,NaN,56,NaN,45,20,137,NaN,90,NaN,248,NaN,148,NaN
62,174,Niger,NaN,2006,21,71,20,NaN,48,NaN,54,37,91,NaN,67,NaN,206,NaN,157,NaN
63,176,Burkina Faso,NaN,2003,39,91,34,NaN,61,NaN,46,21,97,NaN,78,NaN,206,NaN,144,NaN
64,177,Sierra Leone,"d,h",2005,27,83,..,NaN,..,NaN,44,26,159,NaN,108,NaN,268,NaN,179,NaN

In [32]:
hdi_categories = ["HIGH HUMAN DEVELOPMENT", "MEDIUM HUMAN DEVELOPMENT", "LOW HUMAN DEVELOPMENT"]
# Se débarrasser des rangées avec les catégories HDI
# https://stackoverflow.com/a/27360130 & https://stackoverflow.com/a/12098586
dataset = dataset.drop(dataset[dataset["HDI_rank"].isin(hdi_categories)].index, axis=0).reset_index(drop=True)
# Référence pour np.where https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html
# Pensez que cela ressemble à une déclaration du type "if" : where(test est vrai, vrai-quelque chose, faux-quelque chose)
# ceci peut aussi être imbriqué : where(test is true, true-thing, where(new-test is true, true-thing, false-thing))
dataset.loc[:, "HDI category"] = np.where(dataset["HDI_rank"] > 155,
                                     "LOW HUMAN DEVELOPMENT",
                                     np.where(dataset["HDI_rank"] > 70,
                                              "MEDIUM HUMAN DEVELOPMENT",
                                              "HIGH HUMAN DEVELOPMENT"
                                             )
                                    )
dataset.sort_values(by="HDI_rank", inplace=True)
dataset

,HDI_rank,Country,Reference 1,Survey_year,Birth_attended_Poor,Birth_attended_Rich,One-year-olds immunized_Poor,Reference 2,One-year-olds immunized_Rich,Reference 3,...,Child_underheight_ Rich,IMR_Poor,Reference 4,IMR_Rich,Reference 5,Under5_MR_Poor,Reference 6,Under5_MR_Rich,Reference 7,HDI category
0,70,Brazil,NaN,1996,72,99,57,NaN,74,NaN,...,2,83,NaN,29,NaN,99,NaN,33,NaN,HIGH HUMAN DEVELOPMENT
1,73,Kazakhstan,NaN,1999,99,99,69,NaN,62,c,...,8,68,NaN,42,NaN,82,NaN,45,NaN,MEDIUM HUMAN DEVELOPMENT
2,75,Colombia,NaN,2005,72,99,47,NaN,72,NaN,...,3,32,NaN,14,NaN,39,NaN,16,NaN,MEDIUM HUMAN DEVELOPMENT
3,78,Thailand,d,2005-06,93,100,92,e,86,e,...,7,..,NaN,..,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
4,79,Dominican Republic,NaN,1996,89,98,34,NaN,47,NaN,...,2,67,NaN,23,NaN,90,NaN,27,NaN,MEDIUM HUMAN DEVELOPMENT
5,83,Armenia,NaN,2005,96,100,59,e,51,"c,e",...,8,41,NaN,14,NaN,52,NaN,23,NaN,MEDIUM HUMAN DEVELOPMENT
6,84,Turkey,NaN,1998,53,98,28,NaN,70,NaN,...,4,68,NaN,30,NaN,85,NaN,33,NaN,MEDIUM HUMAN DEVELOPMENT
7,86,Jordan,NaN,1997,91,99,21,NaN,17,NaN,...,5,35,NaN,23,NaN,42,NaN,25,NaN,MEDIUM HUMAN DEVELOPMENT
8,87,Peru,NaN,2004-05,34,100,65,e,73,e,...,4,46,NaN,6,NaN,63,NaN,11,NaN,MEDIUM HUMAN DEVELOPMENT
9,90,Philippines,NaN,2003,25,92,56,NaN,83,NaN,...,..,42,NaN,19,NaN,66,NaN,21,NaN,MEDIUM HUMAN DEVELOPMENT
10,95,Paraguay,NaN,1990,41,98,20,NaN,53,NaN,...,3,43,NaN,16,NaN,57,NaN,20,NaN,MEDIUM HUMAN DEVELOPMENT
11,105,Viet Nam,NaN,2002,58,100,44,NaN,92,NaN,...,..,39,NaN,14,NaN,53,NaN,16,NaN,MEDIUM HUMAN DEVELOPMENT
12,107,Indonesia,NaN,1997,21,89,43,NaN,72,NaN,...,..,78,NaN,23,NaN,109,NaN,29,NaN,MEDIUM HUMAN DEVELOPMENT
13,109,Turkmenistan,NaN,2000,97,98,85,NaN,78,NaN,...,17,89,NaN,58,NaN,106,NaN,70,NaN,MEDIUM HUMAN DEVELOPMENT
14,110,Nicaragua,NaN,2001,78,99,64,NaN,71,NaN,...,5,50,NaN,16,NaN,64,NaN,19,NaN,MEDIUM HUMAN DEVELOPMENT
15,111,Moldova,NaN,2005,99,100,86,"c,f",86,f,...,6,20,NaN,16,NaN,29,NaN,17,NaN,MEDIUM HUMAN DEVELOPMENT
16,112,Egypt,NaN,2005,51,96,85,e,91,e,...,14,59,NaN,23,NaN,75,NaN,25,NaN,MEDIUM HUMAN DEVELOPMENT
17,113,Uzbekistan,NaN,1996,92,100,81,NaN,78,NaN,...,31,54,NaN,46,NaN,70,NaN,50,NaN,MEDIUM HUMAN DEVELOPMENT
18,116,Kyrgyzstan,NaN,1997,96,100,69,NaN,73,NaN,...,14,83,NaN,46,NaN,96,NaN,49,NaN,MEDIUM HUMAN DEVELOPMENT
19,117,Bolivia,NaN,2003,27,98,48,e,57,e,...,5,72,g,27,g,105,g,32,g,MEDIUM HUMAN DEVELOPMENT
20,118,Guatemala,NaN,1998-99,9,92,66,NaN,56,NaN,...,8,58,NaN,39,NaN,78,NaN,39,NaN,MEDIUM HUMAN DEVELOPMENT
21,119,Gabon,NaN,2000,67,97,6,NaN,24,NaN,...,12,57,NaN,36,NaN,93,NaN,55,NaN,MEDIUM HUMAN DEVELOPMENT
22,121,South Africa,NaN,1998,68,98,51,NaN,70,NaN,...,..,62,NaN,17,NaN,87,NaN,22,NaN,MEDIUM HUMAN DEVELOPMENT
23,122,Tajikistan,"d,h",2006,69,91,..,NaN,..,NaN,...,21,..,NaN,..,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
24,125,Namibia,NaN,2000,55,97,60,NaN,68,NaN,...,15,36,NaN,23,NaN,55,NaN,31,NaN,MEDIUM HUMAN DEVELOPMENT
25,126,Morocco,NaN,2003-04,30,95,81,e,97,e,...,10,62,NaN,24,NaN,78,NaN,26,NaN,MEDIUM HUMAN DEVELOPMENT
26,128,India,NaN,1998-99,16,84,21,NaN,64,NaN,...,27,97,NaN,38,NaN,141,NaN,46,NaN,MEDIUM HUMAN DEVELOPMENT
27,131,Cambodia,NaN,2005,21,90,56,e,76,e,...,19,101,NaN,34,NaN,127,NaN,43,NaN,MEDIUM HUMAN DEVELOPMENT
28,134,Comoros,NaN,1996,26,85,40,NaN,82,NaN,...,23,87,NaN,65,NaN,129,NaN,87,i,MEDIUM HUMAN DEVELOPMENT
29,135,Ghana,"d,h",2006,..,..,62,e,86,e,...,7,75,NaN,64,NaN,118,NaN,100,NaN,MEDIUM HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,138,Lesotho,NaN,2004,34,83,66,e,69,e,...,25,88,NaN,70,NaN,114,NaN,82,NaN,MEDIUM HUMAN DEVELOPMENT
33,139,Congo,NaN,2005,70,98,29,e,73,e,...,20,91,NaN,56,NaN,135,NaN,85,NaN,MEDIUM HUMAN DEVELOPMENT
34,140,Bangladesh,NaN,2004,3,40,57,e,87,e,...,25,90,NaN,65,NaN,121,NaN,72,NaN,MEDIUM HUMAN DEVELOPMENT
35,142,Nepal,NaN,2001,4,45,54,NaN,82,NaN,...,36,86,NaN,53,NaN,130,NaN,68,NaN,MEDIUM HUMAN DEVELOPMENT
36,143,Madagascar,NaN,2003-04,30,94,32,NaN,80,NaN,...,38,87,NaN,33,NaN,142,NaN,49,NaN,MEDIUM HUMAN DEVELOPMENT
37,144,Cameroon,NaN,2004,29,94,36,NaN,60,NaN,...,12,101,NaN,51,NaN,189,NaN,88,NaN,MEDIUM HUMAN DEVELOPMENT
38,146,Haiti,NaN,2005-06,6,68,34,NaN,56,NaN,...,5,78,NaN,45,NaN,125,NaN,55,NaN,MEDIUM HUMAN DEVELOPMENT
39,148,Kenya,NaN,2003,17,75,40,f,65,f,...,19,96,NaN,62,NaN,149,NaN,91,NaN,MEDIUM HUMAN DEVELOPMENT
40,151,Zimbabwe,NaN,1999,57,94,64,NaN,64,NaN,...,19,59,NaN,44,NaN,100,NaN,62,NaN,MEDIUM HUMAN DEVELOPMENT
41,152,Togo,NaN,1998,25,91,22,NaN,52,NaN,...,11,84,NaN,66,NaN,168,NaN,97,NaN,MEDIUM HUMAN DEVELOPMENT
42,153,Yemen,NaN,1997,7,50,8,NaN,56,NaN,...,35,109,NaN,60,NaN,163,NaN,73,NaN,MEDIUM HUMAN DEVELOPMENT
43,154,Uganda,NaN,2000-01,20,77,27,NaN,43,NaN,...,25,106,NaN,60,NaN,192,NaN,106,NaN,MEDIUM HUMAN DEVELOPMENT
44,156,Senegal,NaN,2005,20,89,59,NaN,65,NaN,...,6,89,NaN,41,NaN,183,NaN,64,NaN,LOW HUMAN DEVELOPMENT
45,157,Eritrea,NaN,2002,7,81,74,NaN,91,NaN,...,18,48,NaN,38,NaN,100,NaN,65,NaN,LOW HUMAN DEVELOPMENT
46,158,Nigeria,NaN,2003,12,84,3,NaN,40,NaN,...,18,133,NaN,52,NaN,257,NaN,79,NaN,LOW HUMAN DEVELOPMENT
47,159,Tanzania (United Republic of),NaN,1999,29,83,53,NaN,78,NaN,...,23,115,NaN,92,NaN,160,NaN,135,NaN,LOW HUMAN DEVELOPMENT
48,160,Guinea,NaN,2005,15,87,29,NaN,45,NaN,...,22,127,NaN,68,NaN,217,NaN,113,NaN,LOW HUMAN DEVELOPMENT
49,161,Rwanda,NaN,2005,27,66,74,NaN,74,NaN,...,30,114,NaN,73,NaN,211,NaN,122,NaN,LOW HUMAN DEVELOPMENT
50,163,Benin,NaN,2001,50,99,49,NaN,73,NaN,...,18,112,NaN,50,NaN,198,NaN,93,NaN,LOW HUMAN DEVELOPMENT
51,164,Malawi,"d,h",2000,43,83,65,NaN,81,NaN,...,23,132,NaN,86,NaN,231,NaN,149,NaN,LOW HUMAN DEVELOPMENT
52,165,Zambia,NaN,2001-02,20,91,64,NaN,80,NaN,...,32,115,NaN,57,NaN,192,NaN,92,NaN,LOW HUMAN DEVELOPMENT
53,166,Côte d'Ivoire,NaN,2005,27,88,..,NaN,..,NaN,...,..,93,NaN,79,NaN,150,NaN,100,NaN,LOW HUMAN DEVELOPMENT
54,169,Ethiopia,NaN,2005,1,27,14,NaN,36,NaN,...,35,80,NaN,60,NaN,130,NaN,92,NaN,LOW HUMAN DEVELOPMENT
55,170,Chad,NaN,2004,4,55,1,NaN,24,NaN,...,32,109,NaN,101,NaN,176,NaN,187,NaN,LOW HUMAN DEVELOPMENT
56,171,Central African Republic,NaN,1994-95,14,82,18,NaN,64,NaN,...,25,132,NaN,54,NaN,193,NaN,98,NaN,LOW HUMAN DEVELOPMENT
57,172,Mozambique,NaN,2003,25,89,45,NaN,90,NaN,...,20,143,NaN,71,NaN,196,NaN,108,NaN,LOW HUMAN DEVELOPMENT
58,173,Mali,NaN,2001,8,82,20,NaN,56,NaN,...,20,137,NaN,90,NaN,248,NaN,148,NaN,LOW HUMAN DEVELOPMENT
59,174,Niger,NaN,2006,21,71,20,NaN,48,NaN,...,37,91,NaN,67,NaN,206,NaN,157,NaN,LOW HUMAN DEVELOPMENT
60,176,Burkina Faso,NaN,2003,39,91,34,NaN,61,NaN,...,21,97,NaN,78,NaN,206,NaN,144,NaN,LOW HUMAN DEVELOPMENT
61,177,Sierra Leone,"d,h",2005,27,83,..,NaN,..,NaN,...,26,159,NaN,108,NaN,268,NaN,179,NaN,LOW HUMAN DEVELOPMENT